### ISSUE TITLE
pbrbasic and pbribl not found textures files 

### ISSUE THREAD

**Issue by mrcmunir** [SaschaWillems/Vulkan#324] opened 2017-04-17 09:26 UTC
[mrc@Mrc-munir bin]$ ./pbribl 
Could not load texture from ./../data/textures/hdr/pisa_cube.ktx
[mrc@Mrc-munir bin]$ ./pbribl 
Could not load texture from ./../data/textures/hdr/pisa_cube.ktx

It's a regresion the folder /hdr/ in textures not found in the github .

**Comment by SaschaWillems** [comment] 2017-04-17 09:27
Duplicate of #321, please see the example's header comment.

**Closed by SaschaWillems** 2017-04-17 09:27 UTC
