### ISSUE TITLE
subpasses example blendAttachmentState does not have any effect 

### ISSUE THREAD

**Issue by kyamant** [SaschaWillems/Vulkan#764] opened 2020-09-14 19:24 UTC
The function `void prepareCompositionPass()` in `subpass.cpp`, just before the creation of the last pipeline (`pipelines.transparent`), there is a block of code for enabling blending (starting with` blendAttachmentState.blendEnable = VK_TRUE`).
Since the models used `samplebuilding_glass.gltf` and` samplebuilding.gltf` are each others complement, they do not have any overlapping meshes thus the enabling of blending has no effect. The fragment shader of the other pipeline outputs `vec4(0.0)`.

**Comment by SaschaWillems** [comment] 2020-09-17 12:49
What line of code are you referring to? There is only one line that actually enables blending, and that is required for the transparent part of the scene.

**Comment by kyamant** [comment] 2020-09-17 12:55
This is wrong, should I close it?

**Comment by SaschaWillems** [comment] 2020-09-17 12:57
Sure, if it's working as intended, feel free to close this issue.

**Closed** 2020-09-17 12:58 UTC
Labels: awaiting feedback
