### ISSUE TITLE
Raytracing example creates invalid spv through glslang

### ISSUE THREAD

**Issue by CaffeinePwrdAl** [SaschaWillems/Vulkan#345] opened 2017-06-20 09:45 UTC
Hi Sascha,

Just wanted to raise that we've seen glslang (even the latest from master) generating invalid SPIR-V code for your Raytracing demp, it gets a type conversion wrong on the Sphere type, and our compiler is trying to adhere closely to the SPIR-V specification.

I'll raise an issue with the working group as well, but just thought I'd point it out if you wanted to use shaderc or run the spv-validator as part of your build.

Cheers,

Alex

------------ Bit more write up ------------

The problem is that there is a type, Sphere, which is used both in an SSBO (Spheres) and also for parameter types (sphereIntersect and SphereNormal).

In SPIR-V the SSBO type must be decorated with information on how the type is laid out in memory, i.e. each field has a byte offset from the start of the struct. But these decorations are only allowed
on SSBO type - this is for various layout reasons.

The SPIR-V generator is _forced_ to generate separate types for the Sphere type when used for SSBO and the Sphere type when used for parameter.
  
Looking at the generated SPIR-V (comp.spv.lst)  there is

-  a %Sphere_0 (line 87), which must be the SSBO type as it is decorated with offsets (line 196),

 - a %Sphere_1 (line 99), which is the type used for the arguments,

- a %Sphere (line 231), which is the type used for the parameters.

I can understand why we need %Sphere_0 and %Sphere_1,  but I don't understand why we need %Sphere as well - I would have thought that %Sphere_1 and %Sphere should be the same.

This causes an invalid assignment when used as the types are not the same.

**Comment by SaschaWillems** [comment] 2017-06-20 19:02
Noticed that too but haven't had the time to dig into the validation and check the root cause, so thx a lot for the explanation and passing this to the WG.

**Comment by eero-t** [comment] 2018-04-20 12:47
Raytracing demo doesn't anymore give validation errors -> fixed with the SPIRV updates?

**Comment by CaffeinePwrdAl** [comment] 2018-05-03 16:10
Our glslang issue is still open, and it appears it is still generating the same invalid SPIR-V where the argument source and the function arguments have non-compatible types.

Interestingly if you apply the -Os argument to glslang which will make glslang run the spv through the optimiser - it does actually causes it to generate valid spir-v that works.

TBH, running the shaders through the optimiser isn't necessarily a bad thing, so that's a potential stop-gap solution.

Alex

**Closed** 2020-07-30 18:49 UTC
Labels: validation
